run	:	Finlandia.prg
	C:\Program Files\GTK3VICE-3.5-win64\bin\x64sc.exe -autostartprgmode 1 Finlandia.prg
Finlandia.prg	:	finland-quick.asm
	vasm6502_oldstyle_win32.exe -Fbin -cbm-prg -o Finlandia.prg finland-quick.asm
