run	:	Snow.prg
	x64sc -autostartprgmode 1 Snow.prg
#	C:\Program Files\GTK3VICE-3.5-win64\bin\x64sc.exe -autostartprgmode 1 Snow.prg

Snow.prg	:	main.asm
	/usr/local/vbcc/bin/vasm6502_oldstyle -Fbin -cbm-prg -o Snow.prg main.asm
#	vasm6502_oldstyle_win32.exe -Fbin -cbm-prg -o Snow.prg main.asm
